global using AutomotiveBrands.Lib.Response.Models;
global using AutomotiveBrands.UserService.Application.Commands.Preferences.Add;
global using AutomotiveBrands.UserService.Application.Queries.Vehicles.List;
global using AutomotiveBrands.UserService.Controllers;
global using AutomotiveBrands.UserService.Test.Infrastructure;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using Xunit;